version: "3.8"

services:
  javapp:
    container_name: javapp
    #build: .
    image: javaimage:latest
    ports:
      - "3308:3306"
    environment:
      - SERVER_PORT=3308
      - MYSQL_URL=jdbc:mysql://localhost:3307/testdb
    depends_on:
      - mysqldb
      - mongodb

  mongodb:
    container_name: mongocnt
    image: mongotest:latest
    ports:
      - "27017:27017"

  mysqldb:
    container_name: testmysql
    image: test/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=aseel2000
      - MYSQL_DATABASE=testdb
    ports:
      - "3307:3306"